stages:

  data_ingestion:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/data_ingestion.py
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw
      
  data_preprocessing:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/data_preprocessing.py
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    params:
      - preprocess.text_col
      - preprocess.out_col
      - preprocess.min_words
    outs:
      - data/processed

    
  feature_engineering:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/feature_engineering.py
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/data/feature_engineering.py
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
    params:
      - feature_engineering.text_col
      - feature_engineering.label_col
      - feature_engineering.min_df
      - feature_engineering.max_df
      - feature_engineering.token_pattern
      - feature_engineering.ngram_range
    outs:
      - data/features


  model_building:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/model_building.py
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/model_building.py
      - data/features/X_train_bow.npz
      - data/features/X_test_bow.npz
      - data/features/y_train.npy
      - data/features/y_test.npy
    params:
      - model_building.features_type
      - model_building.random_state
      - xgboost.learning_rate
      - xgboost.n_estimators
      - xgboost.reg_alpha
      - xgboost.reg_lambda
      - lightgbm.learning_rate
      - lightgbm.n_estimators
      - lightgbm.reg_alpha
      - lightgbm.reg_lambda
    outs:
      - models/xgb_bow_model.joblib
      - models/lgbm_bow_model.joblib


  model_evaluation:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/model_evaluation.py # --serve-mlflow
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/model_evaluation.py

      # modèles entraînés
      - models/xgb_bow_model.joblib
      - models/lgbm_bow_model.joblib

      # données de test
      - data/features/X_test_bow.npz
      - data/features/y_test.npy

      # paramètres
      - params.yaml

    params:
      # features
      - model_building.features_type

      # MLflow
      - mlflow.tracking_uri
      - mlflow.experiment_name

      # XGBoost (loggés dans MLflow)
      - xgboost.learning_rate
      - xgboost.n_estimators
      - xgboost.reg_alpha
      - xgboost.reg_lambda

      # LightGBM (loggés dans MLflow)
      - lightgbm.learning_rate
      - lightgbm.n_estimators
      - lightgbm.reg_alpha
      - lightgbm.reg_lambda

    outs:
      # rapports locaux
      - reports/metrics_summary.json
      - reports/mlflow_artifacts


  register_model:
    cmd: python C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/register_model.py
    deps:
      - C:/Users/abotsi/Desktop/Projet_pro/projet_mlops_ref_basique/src/models/register_model.py
      - params.yaml

      # résumé métriques (sortie de model_evaluation)
      - reports/metrics_summary.json

      # modèles entraînés
      - models/xgb_bow_model.joblib
      - models/lgbm_bow_model.joblib

      # vectorizer BoW
      - models/vectorizers/bow_vectorizer.joblib

    params:
      - model_building.features_type
      - register_model.metric_key
      - mlflow.tracking_uri
      - mlflow.experiment_name
      - mlflow.registry_model_name

    outs:
      - models/production
      - reports/register_summary.json